language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '11'
  - '8'
  - '6'
script:
  - npm run test
  - npm run build
  - npm run lint
after_success:
  - npm run coverage
#   - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run deploy-docs"; fi
#   - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run semantic-release"; fi
# branches:
#   except:
#     - /^v\d+\.\d+\.\d+$/